spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: testtesttest
    password: testtesttest
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 1000
          starttls:
            enable: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: create
  data:
    redis:
      port: 6379
      host: localhost

  batch:
    job:
      enabled: false


# JWT 설정
secret:
  jwt-secret-key: testtesttesttesttesttesttesttesttest
  accessToken-valid-time: 1800000 # 1시간
  refreshToken-valid-time: 604800000 # 일주일

openai:
  model: gpt-3.5-turbo
  api:
    key: temp
    url: temp

cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: testtest
      secret-key: testtest
    s3:
      bucket: kuroom
    stack:
      auto: false
