spring:
  application:
    name: kurum
  profiles:
    active: prod

logging:
  level:
    org.springframework.cache: trace

app:
  oauth2:
    authorizedRedirectUris:
      - http://localhost:5173

---
spring:
  config:
    import: classpath:config/application-prod.yml
    activate:
      on-profile: prod
