logging:
  level:
    org.springframework.cache: trace

app:
  oauth2:
    authorizedRedirectUris:
      - https://kuroom.shop/oauth/callback

---
spring:
  config:
    import: classpath:config/application-prod.yml
    activate:
      on-profile: prod
