package ku_rum.backend.global.dataInit2;

import ku_rum.backend.domain.building.domain.Building;
import ku_rum.backend.domain.building.model.BuildingAbbrev;
import org.springframework.stereotype.Component;
import java.math.BigDecimal;
import java.util.ArrayList;

@Component
public class BuildingInitializer {
  public static ArrayList<Building> initialize() {

    ArrayList<Building> buildings = new ArrayList<>();

    buildings.add(
            Building.of(
                    BuildingAbbrev.행정.getOriginalname(),
                    1L,
                    BuildingAbbrev.행정.name(),
                    BigDecimal.valueOf(37.543075),
                    BigDecimal.valueOf(127.075067)
            )
    );
    //건물
    buildings.add(
            Building.of(
                    BuildingAbbrev.경영.getOriginalname(),
                    2L,
                    BuildingAbbrev.경영.name(),
                    BigDecimal.valueOf(37.544419),
                    BigDecimal.valueOf(127.076370))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.상허관.getOriginalname(),
                    3L,
                    BuildingAbbrev.상허관.name(),
                    BigDecimal.valueOf(37.544292),
                    BigDecimal.valueOf(127.076212))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.사.getOriginalname(),
                    4L,
                    BuildingAbbrev.사.name(),
                    BigDecimal.valueOf(37.544073),
                    BigDecimal.valueOf(127.073994))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.예.getOriginalname(),
                    5L,
                    BuildingAbbrev.예.name(),
                    BigDecimal.valueOf(37.544419),
                    BigDecimal.valueOf(127.073994))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.언어원.getOriginalname(),
                    6L,
                    BuildingAbbrev.언어원.name(),
                    BigDecimal.valueOf(37.542497),
                    BigDecimal.valueOf(127.074584))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.박물관.getOriginalname(),
                    7L,
                    BuildingAbbrev.박물관.name(),
                    BigDecimal.valueOf(37.542373),
                    BigDecimal.valueOf(127.075628)
            )
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.종강.getOriginalname(),
                    8L,
                    BuildingAbbrev.종강.name(),
                    BigDecimal.valueOf(37.542260),
                    BigDecimal.valueOf(127.073637))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.도서관.getOriginalname(),
                    9L,
                    BuildingAbbrev.도서관.name(),
                    BigDecimal.valueOf(37.541939),
                    BigDecimal.valueOf(127.073687))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.의.getOriginalname(),
                    10L,
                    BuildingAbbrev.의.name(),
                    BigDecimal.valueOf(37.541443),
                    BigDecimal.valueOf(127.072313))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.생.getOriginalname(),
                    11L,
                    BuildingAbbrev.생.name(),
                    BigDecimal.valueOf(37.541004),
                    BigDecimal.valueOf(127.074197))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.동.getOriginalname(),
                    12L,
                    BuildingAbbrev.동.name(),
                    BigDecimal.valueOf(37.540242),
                    BigDecimal.valueOf(127.074289))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.입학.getOriginalname(),
                    13L,
                    BuildingAbbrev.입학.name(),
                    BigDecimal.valueOf(37.540323),
                    BigDecimal.valueOf(127.073469))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.산학.getOriginalname(),
                    14L,
                    BuildingAbbrev.산학.name(),
                    BigDecimal.valueOf(37.539701),
                    BigDecimal.valueOf(127.073102))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.수.getOriginalname(),
                    15L,
                    BuildingAbbrev.수.name(),
                    BigDecimal.valueOf(37.539294),
                    BigDecimal.valueOf(127.074676))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.새.getOriginalname(),
                    16L,
                    BuildingAbbrev.새.name(),
                    BigDecimal.valueOf(37.543549),
                    BigDecimal.valueOf(127.077408))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.건.getOriginalname(),
                    17L,
                    BuildingAbbrev.건.name(),
                    BigDecimal.valueOf(37.543391),
                    BigDecimal.valueOf(127.078521))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.부.getOriginalname(),
                    18L,
                    BuildingAbbrev.부.name(),
                    BigDecimal.valueOf(37.543443),
                    BigDecimal.valueOf(127.078225))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.문.getOriginalname(),
                    19L,
                    BuildingAbbrev.문.name(),
                    BigDecimal.valueOf(37.542422),
                    BigDecimal.valueOf(127.078929))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.학생회관.getOriginalname(),
                    20L,
                    BuildingAbbrev.학생회관.name(),
                    BigDecimal.valueOf(37.541873),
                    BigDecimal.valueOf(127.078133))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.공.getOriginalname(),
                    21L,
                    BuildingAbbrev.공.name(),
                    BigDecimal.valueOf(37.541822),
                    BigDecimal.valueOf(127.078845))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.신공.getOriginalname(),
                    22L,
                    BuildingAbbrev.신공.name(),
                    BigDecimal.valueOf(37.540579),
                    BigDecimal.valueOf(127.079472))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.이.getOriginalname(),
                    23L,
                    BuildingAbbrev.이.name(),
                    BigDecimal.valueOf(37.541646),
                    BigDecimal.valueOf(127.080408))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.창.getOriginalname(),
                    24L,
                    BuildingAbbrev.창.name(),
                    BigDecimal.valueOf(37.540757),
                    BigDecimal.valueOf(127.079368))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.KU기술혁신관.getOriginalname(),
                    25L,
                    BuildingAbbrev.KU기술혁신관.name(),
                    BigDecimal.valueOf(37.539690),
                    BigDecimal.valueOf(127.077253))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.기숙사.getOriginalname(),
                    26L,
                    BuildingAbbrev.기숙사.name(),
                    BigDecimal.valueOf(37.539474),
                    BigDecimal.valueOf(127.078203))
    );

    return buildings;
  }
}
